version: '3'
services:
  gdb:
    image: mysql:8.0.33
    ports:
      - "9090:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABSE: trellodb
      MYSQL_TCP_PORT: 3306
    restart: on-failure

  api:
    build: .
    ports:
      - "9091:8080"
    restart: on-failure
    depends_on:
      - gdb



  ui:
    image: nginx
    ports:
      - "9092:80"
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
    restart: on-failure
    depends_on:
      - api